version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 5000:5000

  frontend:
    build:
      context: ./my-chart-app
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - backend
